# Schema for the configuration files of the CKEditor module.

editor.settings.gutenberg:
  type: mapping
  label: 'Gutenberg settings'
  mapping:
    toolbar:
      type: mapping
      label: 'Toolbar configuration'
      mapping:
        rows:
          type: sequence
          label: 'Rows'
          sequence:
            type: sequence
            label: 'Button groups'
            sequence:
              type: mapping
              label: 'Button group'
              mapping:
                name:
                  type: string
                  label: 'Button group name'
                items:
                  type: sequence
                  label: 'Buttons'
                  sequence:
                    type: string
                    label: 'Button'
